export const ADD_NEW_PERSON = "ADD_NEW_PERSON"
export const FETCH_PERSONS = "FETCH_PERSON"
export const CHANGE_ACTIVE_PERSON = "CHANGE_ACTIVE_PERSON"
export const DELETE_PERSON = "DELETE_PERSON"
export const EDIT_PERSON = "EDIT_PERSON"
export const SET_PERSON_BY_ID = "SET_PERSON_BY_ID"
export const CHANGE_EDIT_MODE = "CHANGE_EDIT_MODE"
export const CHANGE_AUTH = "CHANGE_AUTH"

export const FETCH_ALBUMS = "FETCH_ALBUMS"
export const ADD_ALBUM = "ADD_ALBUM"
export const CHANGE_ADD_ALBUM = "CHANGE_ADD_ALBUM"
export const SET_ALBUM_BY_ID= "SET_ALBUM_BY_ID"

export const FETCH_POSTS = "FETCH_POSTS"
export const ADD_POST = "ADD_POST"
export const CHANGE_ADD_POST = "CHANGE_ADD_POST"

export const FETCH_PHOTOS = "FETCH_PHOTOS"
export const ADD_PHOTO = "ADD_PHOTO"
export const EDIT_PHOTO = "EDIT_PHOTO"
export const ADD_LIKE_TO_PHOTO = "ADD_LIKE_TO_PHOTO"
export const ADD_DISLIKE_TO_PHOTO = "ADD_DISLIKE_TO_PHOTO"



